#!/usr/bin/env zsh

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew install neovim
brew install tmux
brew install tig
brew install exa
brew install stow
brew install fzf
brew install htop
brew install rg

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

brew install --cask shureplus-motiv
brew install --cask 1password
brew install --cask spectacle
brew install --cask vial
brew install --cask brave-browser
